const N={v:"1.0.0",vk:"nexus_vfs_1",ck:"nexus_cwd_1",hk:"nexus_hist_1"};
const $=s=>document.querySelector(s);
let py=null,pyReady=false;
const D={"/":{t:"d",c:["home","tmp","etc"]},"/home":{t:"d",c:["nexus"]},"/home/nexus":{t:"d",c:["README.txt","projects"]},"/home/nexus/README.txt":{t:"f",x:"NEXUS OS\n\nTry:\nls\nmkdir myapp\ncd myapp\ntouch hello.txt\nnano hello.txt\npython -c \"print(2+3)\"\nneofetch\nhelp\n"},"/home/nexus/projects":{t:"d",c:[]},"/tmp":{t:"d",c:[]},"/etc":{t:"d",c:[]}};
let fs=load(),cwd=localStorage.getItem(N.ck)||"/home/nexus",hist=JSON.parse(localStorage.getItem(N.hk)||"[]");
function load(){try{return JSON.parse(localStorage.getItem(N.vk))||clone(D)}catch{return clone(D)}}function clone(x){return JSON.parse(JSON.stringify(x))}function save(){localStorage.setItem(N.vk,JSON.stringify(fs));count()}function path(x){if(!x||x===".")return cwd;let a=(x[0]==="/" ? x : cwd+"/"+x).split("/"),o=[];for(const z of a){if(!z||z===".")continue;z===".." ? o.pop():o.push(z)}return"/"+o.join("/")}function par(p){let a=p.split("/").filter(Boolean);a.pop();return"/"+a.join("/")}function base(p){return p==="/"?"/":p.split("/").filter(Boolean).pop()}function ex(p){return Object.hasOwn(fs,p)}function dir(p){return ex(p)&&fs[p].t==="d"}function file(p){return ex(p)&&fs[p].t==="f"}function child(d,n){if(dir(d)&&!fs[d].c.includes(n))fs[d].c.push(n)}
function mkdir(x){x=path(x);if(ex(x))return["e",`mkdir: ${x}: File exists`];let p=par(x);if(!dir(p))return["e","mkdir: parent does not exist"];fs[x]={t:"d",c:[]};child(p,base(x));save();return["s",`created directory: ${x}`]}
function touch(x){x=path(x);if(ex(x))return["e",`touch: ${x}: File exists`];let p=par(x);if(!dir(p))return["e","touch: parent does not exist"];fs[x]={t:"f",x:""};child(p,base(x));save();return["s",`created: ${x}`]}
function cat(x){x=path(x);if(!ex(x))return["e",`cat: ${x}: No such file or directory`];if(!file(x))return["e",`cat: ${x}: Is a directory`];return["",fs[x].x]}
function write(x,c){x=path(x);if(!ex(x)){let r=touch(x);if(r[0]==="e")return r}if(!file(x))return["e","Is a directory"];fs[x].x=c;save();return["s",`saved: ${x}`]}
function rm(x){x=path(x);if(x==="/"||!ex(x))return["e",`rm: cannot remove ${x}`];let all=[];function walk(p){all.push(p);if(dir(p))fs[p].c.forEach(n=>walk((p==="/"?"":p)+"/"+n))}walk(x);all.forEach(p=>delete fs[p]);fs[par(x)].c=fs[par(x)].c.filter(n=>n!==base(x));save();return["s",`removed: ${x}`]}
function count(){let n=Object.values(fs).filter(x=>x.t==="f").length;$("#files").textContent=n;$("#vfs").textContent="MOUNTED"}function prompt(){return`nexus@os:${cwd==="/home/nexus"?"~":cwd}$`}function out(t,c=""){let d=document.createElement("div");d.className=c;d.textContent=t;$("#out").appendChild(d);$("#out").scrollTop=$("#out").scrollHeight}
function toks(s){let a=[],q=null,c="";for(let i=0;i<s.length;i++){let z=s[i];if(q){if(z===q)q=null;else c+=z}else if(z==="\""||z==="'")q=z;else if(/\s/.test(z)){if(c){a.push(c);c=""}}else c+=z}if(c)a.push(c);return a}
function pycode(s){let m=s.match(/^python(?:3)?\s+(?:-c\s+)?([\s\S]+)$/i);if(!m)return null;let c=m[1].trim();if((c[0]==='"'&&c.at(-1)==='"')||(c[0]==="'"&&c.at(-1)==="'"))c=c.slice(1,-1);return c}
function help(){out("NEXUS COMMANDS","info");["ls [path]","pwd","cd <path>","mkdir <name>","touch <file>","cat <file>","rm <path>","nano <file>","clear","neofetch","history","whoami","date","uname",'python -c "print(2+3)"',"python3 -c \"for i in range(5): print(i)\"","signal","arena","about","theme","reset-vfs","exit"].forEach(x=>out("  "+x))}
async function run(s){s=s.trim();if(!s)return;out(prompt()+" "+s,"cmd");hist.push(s);hist=hist.slice(-100);localStorage.setItem(N.hk,JSON.stringify(hist));let a=toks(s),c=a[0].toLowerCase(),v=a.slice(1);
if(c==="python"||c==="python3"){let code=pycode(s);if(!code)return out(`Python ${pyReady?"ready":"loading"}. Use: python -c "print(2+3)"`,"info");if(!pyReady)return out("Python runtime is still loading.","error");out("[PYTHON] executing...","info");try{let r=await py.runPythonAsync(code);if(r!==undefined)out(String(r),"success");out("[PYTHON] exit code 0","success")}catch(e){out(String(e),"error")}return}
if(c==="help")help();
else if(c==="ls"){let p=path(v[0]||".");if(!dir(p))out(`ls: ${p}: not a directory`,"error");else out(fs[p].c.map(n=>fs[(p==="/"?"":p)+"/"+n]?.t==="d"?n+"/":n).join("    "))}
else if(c==="pwd")out(cwd);
else if(c==="cd"){let p=path(v[0]||"/home/nexus");if(dir(p)){cwd=p;localStorage.setItem(N.ck,cwd);$("#prompt").textContent=prompt()}else out("cd: no such directory","error")}
else if(c==="mkdir"){if(!v.length)out("mkdir: missing operand","error");v.forEach(x=>{let r=mkdir(x);out(r[1],r[0])})}
else if(c==="touch"){if(!v.length)out("touch: missing operand","error");v.forEach(x=>{let r=touch(x);out(r[1],r[0])})}
else if(c==="cat"){if(!v.length)out("cat: missing operand","error");v.forEach(x=>{let r=cat(x);out(r[1],r[0])})}
else if(c==="rm"){if(!v.length)out("rm: missing operand","error");v.forEach(x=>{let r=rm(x);out(r[1],r[0])})}
else if(c==="nano"){if(!v[0])out("nano: missing filename","error");else openNano(v[0])}
else if(c==="clear")$("#out").innerHTML="";
else if(c==="neofetch"){out("NEXUS OS","info");out(`OS       : NEXUS OS ${N.v}`);out("Kernel   : NEXUS Virtual Kernel");out("Shell    : NEXUS Shell");out(`Python   : ${pyReady?"Pyodide WASM READY":"LOADING"}`);out("VFS      : LocalStorage");out(`CWD      : ${cwd}`)}
else if(c==="history")hist.forEach((x,i)=>out(`${i+1}  ${x}`));
else if(c==="whoami")out("nexus");else if(c==="date")out(new Date().toString());else if(c==="uname")out("NEXUS-OS nexus-web 1.0.0 wasm browser x86_64");
else if(c==="signal")open("signal");else if(c==="arena")open("arena");else if(c==="about")open("about");
else if(c==="theme")theme();else if(c==="reset-vfs"){if(confirm("Reset NEXUS VFS?")){fs=clone(D);cwd="/home/nexus";save();localStorage.setItem(N.ck,cwd);$("#prompt").textContent=prompt();out("VFS reset.","success")}}
else if(c==="exit")close("terminal");else out(`${c}: command not found. Type 'help' for commands.`,"error")}
$("#cmd").addEventListener("keydown",e=>{if(e.key==="Enter"){let x=$("#cmd").value;$("#cmd").value="";run(x)}});
function openNano(n){let p=path(n);if(!ex(p)){let r=touch(n);if(r[0]==="e")return out(r[1],"error")}if(!file(p))return out("nano: Is a directory","error");$("#filename").value=p;$("#editor").value=fs[p].x;$("#editstatus").textContent="EDITING";open("nano");setTimeout(()=>$("#editor").focus(),50)}
$("#save").onclick=()=>{let r=write($("#filename").value,$("#editor").value);$("#editstatus").textContent=r[1];out(r[1],r[0])};$("#editor").onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();$("#save").click()}}
function open(n){$("#"+n).classList.remove("hidden");if(n==="terminal")setTimeout(()=>$("#cmd").focus(),50);if(n==="signal")signalStart();if(n==="arena")resizeGame()}function close(n){$("#"+n).classList.add("hidden")}
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>open(b.dataset.open));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>close(b.dataset.close));$("#theme").onclick=theme;
function theme(){document.body.classList.toggle("light");localStorage.setItem(N.themeKey,document.body.classList.contains("light")?"light":"dark")}
function toast(t){let d=document.createElement("div");d.className="toast";d.textContent=t;$("#toast").append(d);setTimeout(()=>d.remove(),2500)}

async function loadPy(){try{py=await loadPyodide({indexURL:"https://cdn.jsdelivr.net/pyodide/v0.27.2/full/"});pyReady=true;$("#pyStatus").textContent="PYTHON: READY";$("#pyStat").textContent="READY";$("#foot").textContent="PYTHON WASM READY";toast("Python 3 WebAssembly ready")}catch(e){console.error(e);$("#pyStatus").textContent="PYTHON: ERROR";$("#pyStat").textContent="ERROR";$("#foot").textContent="PYTHON WASM FAILED"}}

setInterval(()=>$("#clock").textContent=new Date().toLocaleTimeString([],{hour12:false}),1000);
const sc=$("#stars"),sx=sc.getContext("2d");let stars=[];function rs(){sc.width=innerWidth;sc.height=innerHeight;stars=Array.from({length:140},()=>({x:Math.random()*sc.width,y:Math.random()*sc.height,r:Math.random()*1.4+.2,s:Math.random()*.4+.05}))}function star(){sx.clearRect(0,0,sc.width,sc.height);sx.fillStyle="#7fffd4";for(let s of stars){s.y+=s.s;if(s.y>sc.height)s.y=0;sx.globalAlpha=.2+s.r/2;sx.beginPath();sx.arc(s.x,s.y,s.r,0,7);sx.fill()}requestAnimationFrame(star)}addEventListener("resize",rs);rs();star();

const cv=$("#sigcanvas"),cx=cv.getContext("2d");let sigFrame=null,phase=0;function signalStart(){let r=cv.getBoundingClientRect();cv.width=r.width*devicePixelRatio;cv.height=r.height*devicePixelRatio;cx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);if(!sigFrame)drawSig()}function drawSig(){let w=cv.clientWidth,h=cv.clientHeight;if(!w)return;cx.clearRect(0,0,w,h);cx.strokeStyle="#00ff9d";cx.beginPath();let amp=+$("#intensity").value/100;phase+=.03+(+$("#speed").value)/1000;for(let x=0;x<=w;x++){let y=h/2+Math.sin(x/w*15+phase)*55*amp+(Math.random()-.5)*15*amp;x?cx.lineTo(x,y):cx.moveTo(x,y)}cx.stroke();sigFrame=requestAnimationFrame(drawSig)}

const gc=$("#gamecanvas"),gx=gc.getContext("2d"),game={p:{x:300,y:250,hp:100},b:[],e:[],k:{},m:{x:500,y:250,d:false},score:0,spawn:0,shot:0},gameOn=false,fire=false;
function resizeGame(){let r=gc.getBoundingClientRect();if(!r.width)return;gc.width=r.width*devicePixelRatio;gc.height=r.height*devicePixelRatio;gx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function startGame(){resizeGame();game.p={x:gc.clientWidth/2,y:gc.clientHeight/2,hp:100};game.b=[];game.e=[];game.score=0;game.spawn=0;game.shot=0;gameOn=true;$("#gameover").classList.add("hidden");loop()}
function enemy(){let w=gc.clientWidth,h=gc.clientHeight,s=Math.floor(Math.random()*4),x=s===1?w+20:s===3?-20:Math.random()*w,y=s===0?-20:s===2?h+20:Math.random()*h;game.e.push({x,y,r:14,s:.8+Math.random()*1.2,h:1})}
function shoot(){if(!gameOn||game.shot)return;game.shot=8;let dx=game.m.x-game.p.x,dy=game.m.y-game.p.y,l=Math.hypot(dx,dy)||1;game.b.push({x:game.p.x,y:game.p.y,vx:dx/l*9,vy:dy/l*9,l:80})}
function updateGame(){let p=game.p,dx=(game.k.d?1:0)-(game.k.a?1:0),dy=(game.k.s?1:0)-(game.k.w?1:0),l=Math.hypot(dx,dy)||1;p.x+=dx/l*4;p.y+=dy/l*4;p.x=Math.max(14,Math.min(gc.clientWidth-14,p.x));p.y=Math.max(14,Math.min(gc.clientHeight-14,p.y));if(game.m.d||fire)shoot();if(game.shot)game.shot--;game.b.forEach(b=>{b.x+=b.vx;b.y+=b.vy;b.l--});game.b=game.b.filter(b=>b.l>0);if(--game.spawn<=0){enemy();game.spawn=Math.max(15,50-game.score/10)}for(let e of game.e){let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*e.s;e.y+=dy/d*e.s;if(d<p.r+e.r)p.hp-=.4}for(let b of game.b)for(let e of game.e)if(Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){e.h=0;b.l=0;game.score++}game.e=game.e.filter(e=>e.h);$("#score").textContent=`SCORE: ${game.score} HP: ${Math.max(0,game.p.hp|0)}`;if(p.hp<=0){gameOn=false;$("#gameover").classList.remove("hidden");$("#gameover h2").textContent="GAME OVER";$("#start").textContent="RESTART"}}
function drawGame(){let w=gc.clientWidth,h=gc.clientHeight;gx.fillStyle="#020505";gx.fillRect(0,0,w,h);gx.strokeStyle="#0b2720";for(let x=0;x<w;x+=40){gx.beginPath();gx.moveTo(x,0);gx.lineTo(x,h);gx.stroke()}for(let y=0;y<h;y+=40){gx.beginPath();gx.moveTo(0,y);gx.lineTo(w,y);gx.stroke()}let p=game.p;gx.fillStyle="#00ff9d";gx.beginPath();gx.arc(p.x,p.y,14,0,7);gx.fill();gx.fillStyle="#00d9ff";game.b.forEach(b=>{gx.beginPath();gx.arc(b.x,b.y,3,0,7);gx.fill()});gx.fillStyle="#ff416c";game.e.forEach(e=>{gx.beginPath();gx.arc(e.x,e.y,e.r,0,7);gx.fill()})}
function loop(){if(!gameOn)return;updateGame();drawGame();requestAnimationFrame(loop)}
$("#start").onclick=startGame;addEventListener("resize",resizeGame);gc.onmousemove=e=>{let r=gc.getBoundingClientRect();game.m.x=e.clientX-r.left;game.m.y=e.clientY-r.top};gc.onmousedown=()=>game.m.d=true;addEventListener("mouseup",()=>game.m.d=false);addEventListener("keydown",e=>game.k[e.key.toLowerCase()]=true);addEventListener("keyup",e=>game.k[e.key.toLowerCase()]=false);$("#fire").onpointerdown=()=>fire=true;$("#fire").onpointerup=()=>fire=false;

async function boot(){if(localStorage.getItem(N.themeKey)==="light")document.body.classList.add("light");count();$("#prompt").textContent=prompt();for(let x of [20,45,70,100]){await new Promise(r=>setTimeout(r,180));$("#bar").style.width=x+"%"}setTimeout(()=>{$("#boot").remove();$("#app").classList.remove("hidden")},400);out("NEXUS OS terminal initialized.","success");out("Persistent VFS mounted at /home/nexus");out("Type 'help' for commands.","info");loadPy()}boot();